// ---------------------------------------------------------------------------
// TransactionService — business logic for money transfers, history, dashboard.
//
// Layer contract
// --------------
// • All DB access goes through repositories — never touches Prisma directly
//   except for the atomic $transaction block.
// • Returns plain output objects; throws typed AppError subclasses.
// • No Express types, no req/res.
// ---------------------------------------------------------------------------
import { PrismaClient, Prisma } from '../generated/prisma/client';
import { UserRepository } from '../repositories/user.repository';
import { WalletRepository } from '../repositories/wallet.repository';
import { TransactionRepository, TransactionWithDetails } from '../repositories/transaction.repository';
import { NotificationRepository } from '../repositories/notification.repository';
import { NotificationType } from './notification.service';
import { IdempotencyService } from './idempotency.service';
import { NotFoundError, UnprocessableEntityError, ConflictError, ForbiddenError } from '../utils/errors';
import { transferSchema } from '../validators/transaction.validator';

// ---------------------------------------------------------------------------
// Input / output types
// ---------------------------------------------------------------------------

export interface TransferInput {
  senderUserId: string;
  receiverPayflowId: string;
  amount: number;
  note?: string | undefined;
  /** UUID generated by the client. When provided, enforces exactly-once execution. */
  idempotencyKey?: string | undefined;
}

export interface TransferResult {
  transactionId: string;
  senderBalance: string;
  receiverBalance: string;
  receiverName: string;
  receiverPayflowId: string;
}

export interface TransactionHistoryItem {
  id: string;
  amount: string;
  /** PENDING | COMPLETED | FAILED */
  status: string;
  /** ADD_MONEY | TRANSFER */
  type: string;
  /** CREDIT | DEBIT */
  direction: string;
  note: string | null;
  createdAt: Date;
  senderPayflowId: string;
  receiverPayflowId: string;
  senderEmail: string;
  receiverEmail: string;
}

export interface DashboardResult {
  balance: string;
  totalSent: string;
  totalReceived: string;
  recentTransactions: TransactionHistoryItem[];
  // Extended statistics
  monthlySpending: string;
  moneyReceivedThisMonth: string;
  moneySentToday: string;
  largestTransaction: TransactionHistoryItem | null;
  transactionCount: number;
}

// ---------------------------------------------------------------------------
// TransactionService
// ---------------------------------------------------------------------------
export class TransactionService {
  constructor(
    private readonly db: PrismaClient,
    private readonly userRepository: UserRepository,
    private readonly walletRepository: WalletRepository,
    private readonly transactionRepository: TransactionRepository,
    private readonly notificationRepository?: NotificationRepository,
    private readonly idempotencyService?: IdempotencyService,
  ) {}

  // ── Fire-and-forget notification helper ──────────────────────────────────
  private notify(
    userId: string,
    type: NotificationType,
    title: string,
    body: string,
    refId?: string,
  ): void {
    if (!this.notificationRepository) return;
    const input = refId !== undefined
      ? { userId, type, title, body, refId }
      : { userId, type, title, body };
    void this.notificationRepository.create(input);
  }

  // ── Serialise a TransactionWithDetails row ─────────────────────────────────
  private toHistoryItem(tx: TransactionWithDetails): TransactionHistoryItem {
    return {
      id: tx.id,
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call
      amount: tx.amount.toString(),
      status: tx.status,
      type: tx.type,
      direction: tx.direction,
      note: tx.note,
      createdAt: tx.createdAt,
      senderPayflowId: tx.sender.payflowId,
      receiverPayflowId: tx.receiver.payflowId,
      senderEmail: tx.sender.email,
      receiverEmail: tx.receiver.email,
    };
  }

  // ── Transfer money ────────────────────────────────────────────────────────
  async transferMoney(input: TransferInput): Promise<TransferResult> {
    // 1. Validate input
    const { receiverPayflowId, amount, note } = transferSchema.parse({
      receiverPayflowId: input.receiverPayflowId,
      amount: input.amount,
      note: input.note,
    });

    // 1b. Idempotency check — short-circuit if the key was already processed.
    //     Returns cached result for duplicate requests; throws 409 for mismatched payloads.
    let idempotencyMeta:
      | { recordId: string; requestHash: string; expiresAt: Date }
      | undefined;

    if (input.idempotencyKey !== undefined && this.idempotencyService !== undefined) {
      const check = await this.idempotencyService.checkOrPrepare(
        input.senderUserId,
        input.idempotencyKey,
        // Spread only defined keys to satisfy exactOptionalPropertyTypes.
        note !== undefined
          ? { receiverPayflowId, amount, note }
          : { receiverPayflowId, amount },
      );
      if (check.hit) {
        // Duplicate request — return the original response immediately.
        return check.response;
      }
      idempotencyMeta = {
        recordId:    check.recordId,
        requestHash: check.requestHash,
        expiresAt:   check.expiresAt,
      };
    }

    // 2. Find sender
    const sender = await this.userRepository.findById(input.senderUserId);
    if (sender === null) {
      throw new NotFoundError('Sender not found');
    }

    // 3. Find receiver by payflowId
    const receiver = await this.userRepository.findByPayflowId(receiverPayflowId);
    if (receiver === null) {
      throw new NotFoundError(`No user found with PayFlow ID: ${receiverPayflowId}`);
    }

    // 4. Reject self-transfer
    if (sender.id === receiver.id) {
      throw new ConflictError('Cannot transfer money to yourself');
    }

    // 5. Get sender wallet — auto-create for legacy users without one
    let senderWallet = await this.walletRepository.findByUserId(sender.id);
    if (senderWallet === null) {
      senderWallet = await this.walletRepository.create({ userId: sender.id });
    }

    // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    const decimalAmount = new Prisma.Decimal(amount);
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    if (senderWallet.balance.lessThan(decimalAmount)) {
      throw new UnprocessableEntityError('Insufficient balance');
    }

    // 6. Get receiver wallet — auto-create for legacy users without one
    let receiverWallet = await this.walletRepository.findByUserId(receiver.id);
    if (receiverWallet === null) {
      receiverWallet = await this.walletRepository.create({ userId: receiver.id });
    }

    // 7. Single atomic $transaction block:
    //      • debit sender wallet
    //      • credit receiver wallet
    //      • create DEBIT record  (sender's ledger entry)
    //      • create CREDIT record (receiver's ledger entry)
    //      • write idempotency record (if key provided)
    //    All writes succeed or all roll back.
    const result = await this.db.$transaction(async (tx) => {
      const txClient = tx as unknown as PrismaClient;

      const updatedSenderWallet = await txClient.wallet.update({
        where: { userId: sender.id },
        data: { balance: { decrement: decimalAmount } },
      });

      const updatedReceiverWallet = await txClient.wallet.update({
        where: { userId: receiver.id },
        data: { balance: { increment: decimalAmount } },
      });

      // Sender's view: DEBIT (money left their wallet)
      const debitRecord = await txClient.transaction.create({
        data: {
          senderId: sender.id,
          receiverId: receiver.id,
          amount: decimalAmount,
          status: 'COMPLETED',
          type: 'TRANSFER',
          direction: 'DEBIT',
          note: note ?? null,
        },
      });

      // Receiver's view: CREDIT (money arrived in their wallet)
      const creditRecord = await txClient.transaction.create({
        data: {
          senderId: sender.id,
          receiverId: receiver.id,
          amount: decimalAmount,
          status: 'COMPLETED',
          type: 'TRANSFER',
          direction: 'CREDIT',
          note: note ?? null,
        },
      });

      return { updatedSenderWallet, updatedReceiverWallet, debitRecord, creditRecord };
    });

    // 8. Build the result object before conditionally persisting the idempotency key.
    const receiverDisplayName = receiver.payflowId.split('@')[0] ?? receiver.payflowId;
    const senderDisplayName = sender.payflowId.split('@')[0] ?? sender.payflowId;
    const amtStr = amount.toFixed(2);

    const transferResult: TransferResult = {
      transactionId: result.debitRecord.id,
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call
      senderBalance: result.updatedSenderWallet.balance.toString(),
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call
      receiverBalance: result.updatedReceiverWallet.balance.toString(),
      receiverName: receiverDisplayName,
      receiverPayflowId: receiver.payflowId,
    };

    // 8b. Persist idempotency key in a separate write now that we have the result.
    //     This is intentionally outside the main $transaction: if this write fails
    //     the transfer has already committed — we log and continue so the caller
    //     still gets their result. The worst-case outcome is a duplicate on an
    //     extraordinary retry, which is mitigated by the client holding the key.
    if (
      input.idempotencyKey !== undefined &&
      this.idempotencyService !== undefined &&
      idempotencyMeta !== undefined
    ) {
      try {
        await this.idempotencyService.persistInTransaction(
          // Pass the db client directly — outside the main $transaction.
          this.db,
          idempotencyMeta.recordId,
          input.senderUserId,
          input.idempotencyKey,
          idempotencyMeta.requestHash,
          transferResult,
          idempotencyMeta.expiresAt,
        );
      } catch {
        // Unique-constraint violation: a concurrent request with the same key
        // already committed. Safe to swallow — the transfer is done.
      }
    }

    // 9. Fire-and-forget notifications for both parties
    this.notify(
      sender.id,
      NotificationType.MONEY_SENT,
      'Money Sent',
      `You sent ₹${amtStr} to ${receiverDisplayName}.`,
      result.debitRecord.id,
    );
    this.notify(
      receiver.id,
      NotificationType.MONEY_RECEIVED,
      'Money Received',
      `You received ₹${amtStr} from ${senderDisplayName}.`,
      result.creditRecord.id,
    );

    return transferResult;
  }

  // ── Get single transaction by id ──────────────────────────────────────────
  // Only the sender or receiver may access a transaction record.
  // Throws NotFoundError if the id does not exist.
  // Throws ForbiddenError if the requesting user is neither party.
  async getById(transactionId: string, requestingUserId: string): Promise<TransactionHistoryItem> {
    const tx = await this.transactionRepository.findByIdWithDetails(transactionId);
    if (tx === null) {
      throw new NotFoundError('Transaction not found');
    }
    if (tx.senderId !== requestingUserId && tx.receiverId !== requestingUserId) {
      throw new ForbiddenError('You do not have access to this transaction');
    }
    return this.toHistoryItem(tx);
  }

  // ── Transaction history ────────────────────────────────────────────────────
  // Returns all transactions for the user (sent + received), newest first.
  async getHistory(userId: string): Promise<TransactionHistoryItem[]> {
    const rows = await this.transactionRepository.findByUserWithDetails(userId);
    return rows.map((r) => this.toHistoryItem(r));
  }

  // ── Dashboard ─────────────────────────────────────────────────────────────
  // Aggregates balance + totals + stats + recent 5 transactions in parallel.
  async getDashboard(userId: string): Promise<DashboardResult> {
    const [
      walletOrNull,
      totalSentDecimal,
      totalReceivedDecimal,
      monthlySendingDecimal,
      monthlyReceivedDecimal,
      sentTodayDecimal,
      largestTx,
      txCount,
      recent,
    ] = await Promise.all([
      this.walletRepository.findByUserId(userId),
      this.transactionRepository.sumSent(userId),
      this.transactionRepository.sumReceived(userId),
      this.transactionRepository.sumSentThisMonth(userId),
      this.transactionRepository.sumReceivedThisMonth(userId),
      this.transactionRepository.sumSentToday(userId),
      this.transactionRepository.findLargest(userId),
      this.transactionRepository.countByUser(userId),
      this.transactionRepository.findByUserWithDetails(userId, 5),
    ]);

    // Auto-create wallet for users who registered before auto-creation was wired
    const wallet = walletOrNull ?? await this.walletRepository.create({ userId });

    return {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call
      balance: wallet.balance.toString(),
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call
      totalSent: totalSentDecimal.toString(),
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call
      totalReceived: totalReceivedDecimal.toString(),
      recentTransactions: recent.map((r) => this.toHistoryItem(r)),
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call
      monthlySpending: monthlySendingDecimal.toString(),
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call
      moneyReceivedThisMonth: monthlyReceivedDecimal.toString(),
      // eslint-disable-next-line @typescript-eslint/no-unsafe-call
      moneySentToday: sentTodayDecimal.toString(),
      largestTransaction: largestTx !== null ? this.toHistoryItem(largestTx) : null,
      transactionCount: txCount,
    };
  }
}
